RealState/Models/ErrorViewModel.cs
using System;

namespace RealState.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RealState/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RealState.Models;

namespace RealState.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RealState/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Service.RepositoryService.Intefaces;

namespace RealState.Controllers
{
    public class HouseController : Controller
    {
        private readonly IHouseRepository _houseRepository;
        private readonly IOwnerRepository _ownerRepository;


        public HouseController(IHouseRepository houseRepository, IOwnerRepository ownerRepository)
        {
            _houseRepository = houseRepository;
            _ownerRepository = ownerRepository;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _houseRepository.GetAllHouses());

            }
            catch (Exception)
            {

                throw;
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Tb_House model,string phone)
        {
            if (await _ownerRepository.OwnerExists(phone))
            {
                var owner = await _ownerRepository.GetOwnerByphone(phone);
                if (ModelState.IsValid)
                {
                    Tb_House house = new Tb_House
                    {
                        Address = model.Address,
                        EditAt = DateTime.Now,
                        CreateAt = DateTime.Now,
                        IsDeleted = false,
                        Meters = model.Meters,
                        Name = model.Name,
                        Type = model.Type,
                        OwnerId=owner.Id
                    };
                    await _houseRepository.InsertHouse(house);
                    return RedirectToAction(nameof(Index));
                }
                
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Phon number didnt exist in owners");
            }
            return View();
        }
        public async Task<IActionResult> EditAsync(int id)
        {
            var house = await _houseRepository.GetHouseById(id);
            return View(house);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Tb_House model, string phone)
        {

            if (await _ownerRepository.OwnerExists(phone))
            {
                var owner = await _ownerRepository.GetOwnerByphone(phone);
                if (ModelState.IsValid)
                {
                    var house = await _houseRepository.GetHouseById(model.Id);
                    house.Address = model.Address;
                    house.EditAt = DateTime.Now;
                    house.Meters = model.Meters;
                    house.Name = model.Name;
                    house.OwnerId = owner.Id;
                    house.Type = model.Type;
                    await _houseRepository.UpdateHouse(house);
                    return RedirectToAction(nameof(Index));

                }

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Phon number didnt exist in owners");
            }
            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _houseRepository.DeleteHouse(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UnDelete(int id)
        {
            await _houseRepository.UnDeleteHouse(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Deleted()
        {
            return View(await _houseRepository.GetDeletedHouses());
        }
    }
}

RealState/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Service.RepositoryService.Intefaces;

namespace RealState.Controllers
{
    public class OwnerController : Controller
    {
        private readonly IOwnerRepository _ownerRepository;

        public OwnerController(IOwnerRepository ownerRepository)
        {
            _ownerRepository = ownerRepository;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _ownerRepository.GetAllOwners());
        }
        public async Task<IActionResult> ShowOwnersHouse(int id)
        {

            return View(await _ownerRepository.GetOwnerHouses(id));
        }
    }
}

RealState/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RealState/Views/House/Create.cshtml
@model DAL.Models.Tb_House

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tb_House</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meters" class="control-label"></label>
                <input asp-for="Meters" class="form-control" />
                <span asp-validation-for="Meters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Phone</label>
                <input  name="phone" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@Html.GetEnumSelectList<HouseType>()"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RealState/Views/House/Deleted.cshtml
@model IEnumerable<DAL.Models.Tb_House>

@{
    ViewData["Title"] = "Deleted";
}

<h1>Deleted House</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Meters)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EditAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Meters)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EditAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tb_Owner.Name)  @Html.DisplayFor(modelItem => item.Tb_Owner.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tb_Owner.Phone)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Undelete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you wish to Undelete this House?');">UnDelete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RealState/Views/House/Edit.cshtml
@model DAL.Models.Tb_House

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tb_House</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meters" class="control-label"></label>
                <input asp-for="Meters" class="form-control" />
                <span asp-validation-for="Meters" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Phone</label>
                <input name="phone" class="form-control" value="@Model.Tb_Owner.Phone" />
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@Html.GetEnumSelectList<HouseType>()"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RealState/Views/House/Index.cshtml
@model IEnumerable<DAL.Models.Tb_House>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>|
    <a asp-action="Deleted">Deleted</a>|
    <a asp-controller="Owner" asp-action="index">Owners</a>|
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Meters)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EditAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Meters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EditAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tb_Owner.Name)  @Html.DisplayFor(modelItem => item.Tb_Owner.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tb_Owner.Phone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you wish to delete this House?');">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RealState/Views/Owner/Index.cshtml
@model IEnumerable<DAL.Models.Tb_Owner>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a asp-action="ShowOwnersHouse" asp-route-id="@item.Id">Show Houses</a>
            </td>
        </tr>
}
    </tbody>
</table>

RealState/Views/Owner/ShowOwnersHouse.cshtml
@model IEnumerable<DAL.Models.Tb_House>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>|
    <a asp-action="Deleted">Deleted</a>|
    <a asp-controller="Owner" asp-action="index">Owners</a>|
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Meters)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EditAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tb_Owner.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Meters)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EditAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tb_Owner.Name)  @Html.DisplayFor(modelItem => item.Tb_Owner.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tb_Owner.Phone)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you wish to delete this House?');">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RealState/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RealState</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RealState</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Index">Houses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RealState - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>